### ISSUE TITLE
Missing Sentinel Collections

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#105]
### Please describe the expected behaviour
All Sentinel Collections should be added to the portal, so we don't encounter errors like this in the future.
The harvester should be able to collect the Sentinel collections, and not fail.

### Please describe the actual behaviour
There are collections missing and the Sentinel harvester fails. With the following error:

````
2019-10-22 10:32:16,375 WARNI [ckanext.nextgeossharvest.lib.esa_base] No collection for Sentinel-3 product S3A_SY_2_VG1____20190923T111721_20190924T111721_20190929T113258_NORTH_ASIA________LN2_O_NT_002
Traceback (most recent call last):
  File "/usr/lib/ckan/nextgeoss/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/nextgeoss/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/nextgeoss/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/nextgeoss/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 193, in command
    fetch_callback(consumer, method, header, body)
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-harvest/ckanext/harvest/queue.py", line 407, in fetch_callback
    fetch_and_import_stages(harvester, obj)
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-harvest/ckanext/harvest/queue.py", line 424, in fetch_and_import_stages
    success_import = harvester.import_stage(obj)
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 417, in import_stage
    package = self._create_or_update_dataset(harvest_object, status)
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 156, in _create_or_update_dataset
    parsed_content = self._parse_content(harvest_object.content)
  File "/home/gulic/ckan/lib/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/lib/esa_base.py", line 288, in _parse_content
    item['title'] = item['collection_name']
KeyError: 'collection_name'
````
````
ng_ckan_dev   | 2019-10-03 12:10:29,094 INFO  [ckanext.harvest.queue] Received harvest object id: 59abf15d-e196-4d12-bb8f-9a052735a5c5
ng_ckan_dev   | 2019-10-03 12:10:29,113 DEBUG [ckanext.nextgeossharvest.lib.nextgeoss_base.import] Import stage for harvest object with GUID 59abf15d-e196-4d12-bb8f-9a052735a5c5
ng_ckan_dev   | 2019-10-03 12:10:29,114 DEBUG [ckanext.nextgeossharvest.lib.nextgeoss_base] Using config: {u'end_date': u'2019-10-02T23:59:59.999Z', u'update_all': False, u'make_private': False, u'source': u'esa_noa', u'skip_raw': True, u'timeout': 4, u'datasets_per_job': 99, u'start_date': u'2019-10-01T00:00:00.000Z'}
ng_ckan_dev   | 2019-10-03 12:10:29,121 WARNI [ckanext.nextgeossharvest.lib.esa_base] No collection for Sentinel-3 product S3B_SY_2_SYN____20190929T082609_20190929T082909_20190930T230432_0179_030_235_2160_LN2_O_NT_002
ng_ckan_dev   | Traceback (most recent call last):
ng_ckan_dev   |   File "/usr/bin/paster", line 11, in <module>
ng_ckan_dev   |     load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ng_ckan_dev   |     invoke(command, command_name, options, args[1:])
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ng_ckan_dev   |     exit_code = runner.run(args)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ng_ckan_dev   |     result = self.command()
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 193, in command
ng_ckan_dev   |     fetch_callback(consumer, method, header, body)
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 407, in fetch_callback
ng_ckan_dev   |     fetch_and_import_stages(harvester, obj)
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 424, in fetch_and_import_stages
ng_ckan_dev   |     success_import = harvester.import_stage(obj)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 409, in import_stage
ng_ckan_dev   |     package = self._create_or_update_dataset(harvest_object, status)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 154, in _create_or_update_dataset
ng_ckan_dev   |     parsed_content = self._parse_content(harvest_object.content)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/esa_base.py", line 238, in _parse_content
ng_ckan_dev   |     item['title'] = item['collection_name']
ng_ckan_dev   | KeyError: 'collection_name'
````

### What steps can be taken to reproduce the issue?
We encountered this error running the NOA harvester.

The following configurations were used for the testing:
````
{
  "source": "esa_noa",
  "update_all": false,
  "datasets_per_job": 100,
  "timeout": 4,
  "skip_raw": true,
  "make_private": false
}
````
````
{
  "source": "esa_noa",
  "update_all": false,
  "start_date": "2019-10-01T00:00:00.000Z",
  "end_date": "2019-10-02T23:59:59.999Z",
  "datasets_per_job": 99,
  "timeout": 4,
  "skip_raw": true,
  "make_private": false
}
````
Try to run the harvester and check the logs.

**Comment by JGulic** [comment]
@davidcordeiro-deimos can you create a PR for this?

**Comment by davidcordeiro-deimos** [comment]
Yes, I was just finishing some local tests, as soon as I am done, I will create a PR.

**Comment by JGulic** [comment]
merged on master. closing
